// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzaqleivnlpfpautjqiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16YXFsZWl2bmxwZnBhdXRqcWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTkyNDAsImV4cCI6MjA2MDk3NTI0MH0.y6L45AawPssFQ6W2hMTK6oBbkTEnbnXMotXMSiuM1ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);